setUpUser
NOOBDY/you-owe-me-money pull request #6
Opened 2022-12-16 14:37 UTC by KatoToyoki

2022-12-16 14:40 UTC, Chinococo approved these changes

2022-12-16 15:59 UTC, NOOBDY requested changes
fix pylint issues

2022-12-24 08:36 UTC, Chinococo approved these changes

2022-12-24 08:37 UTC, Chinococo approved these changes

2022-12-24 08:37 UTC, Chinococo approved these changes

2022-12-24 11:41 UTC, NOOBDY requested changes
needs to merge changes made in #8

2022-12-30 03:33 UTC, KatoToyoki commented
there is a type error in record.py
like the record_id is str in the constructor,  but in function "get_record_id" your return type is int

and i don't know somehow i have another error said ""datetime" is not defined" but you indeed from datetime import date (I refresh the window but it still exist)

2022-12-30 16:16 UTC, NOOBDY approved these changes

2022-12-30 16:17 UTC, merged